version: '2'
services:
  postgres:
    image: postgres:11
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: transactions
      POSTGRES_PASSWORD: transactions
      POSTGRES_DB: transactions
